"""P341-P350 deterministic production operational-evidence boundary.

This layer combines already-produced release/readiness, runtime, diagnostics and
audit evidence without fabricating any evidence or weakening existing gates.
"""
from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from typing import Mapping, Sequence, Any

from .production_readiness_attestation_v1 import ReadinessAttestation
from .diagnostics_integrity_v1 import validate_bundle, verify_bundle
from .diagnostics_audit_bridge_v1 import verify_bridged_events

@dataclass(frozen=True)
class OperationalEvidence:
    ready: bool
    checks: tuple[tuple[str, bool], ...]
    fingerprint: str
    errors: tuple[str, ...]


def _fingerprint(payload: Mapping[str, Any]) -> str:
    raw = json.dumps(
        dict(payload), ensure_ascii=False, sort_keys=True, separators=(",", ":")
    ).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def attest_operational_evidence(
    *,
    app_version: str,
    readiness: ReadinessAttestation,
    runtime_audit: Mapping[str, Any],
    diagnostics_bundle: Mapping[str, Any],
    audit_events: Sequence[Mapping[str, Any]],
) -> OperationalEvidence:
    """Return a fail-closed operational evidence decision.

    Inputs are evidence generated by existing platform boundaries. This function
    only validates and correlates them; it does not generate, repair or bypass
    evidence.
    """
    errors: list[str] = []
    checks: list[tuple[str, bool]] = []

    app_version = str(app_version).strip()
    version_ok = bool(app_version) and app_version == str(
        diagnostics_bundle.get("app_version", "")
    ).strip()
    checks.append(("application_version_consistency", version_ok))
    if not version_ok:
        errors.append("application version does not match diagnostics bundle")

    readiness_ok = bool(readiness.ready)
    checks.append(("production_readiness_attestation", readiness_ok))
    if not readiness_ok:
        errors.extend(f"readiness: {e}" for e in readiness.errors)

    runtime_ok = runtime_audit.get("valid") is True
    checks.append(("runtime_audit", runtime_ok))
    if not runtime_ok:
        errors.append("runtime audit is not valid")

    diagnostics_errors = validate_bundle(diagnostics_bundle)
    diagnostics_ok = not diagnostics_errors and verify_bundle(diagnostics_bundle)
    checks.append(("diagnostics_bundle_integrity", diagnostics_ok))
    errors.extend(f"diagnostics: {e}" for e in diagnostics_errors)
    if diagnostics_errors == [] and not diagnostics_ok:
        errors.append("diagnostics bundle fingerprint mismatch")

    audit_ok = verify_bridged_events(audit_events)
    checks.append(("audit_chain_integrity", audit_ok))
    if not audit_ok:
        errors.append("audit chain integrity verification failed")

    payload = {
        "app_version": app_version,
        "readiness_fingerprint": readiness.fingerprint,
        "readiness_ready": readiness.ready,
        "runtime_valid": runtime_ok,
        "diagnostics_sha256": diagnostics_bundle.get("sha256", ""),
        "audit_event_count": len(audit_events),
        "checks": tuple(checks),
        "errors": tuple(errors),
    }
    return OperationalEvidence(
        ready=not errors,
        checks=tuple(checks),
        fingerprint=_fingerprint(payload),
        errors=tuple(errors),
    )
