"""Master product map for StructuralPro.

This is a planning/architecture registry, not a claim that every leaf is already
implemented. Existing executable capabilities remain owned by their current
modules; this map provides a stable whole-product destination without replacing
or removing them.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class ProductNode:
    key: str
    title: str
    children: tuple["ProductNode", ...] = ()


def _n(key: str, title: str, *children: ProductNode) -> ProductNode:
    return ProductNode(key, title, tuple(children))


MASTER_PRODUCT_MAP: Final[ProductNode] = _n(
    "structuralpro", "StructuralPro",
    _n("project", "مدیریت پروژه",
       _n("project_info", "اطلاعات پروژه"),
       _n("team", "تیم و دسترسی"),
       _n("files", "فایل‌ها و اسناد"),
       _n("versions", "نسخه‌ها"),
       _n("templates", "قالب‌ها"),
       _n("backup", "پشتیبان‌گیری و بازیابی")),
    _n("architecture", "معماری",
       _n("plans", "پلان"),
       _n("elevations", "نما"),
       _n("sections", "مقطع"),
       _n("rooms", "فضاها و اتاق‌ها"),
       _n("walls", "دیوار و تیغه"),
       _n("openings", "در و پنجره و بازشو"),
       _n("floors_roofs", "کف و سقف و بام"),
       _n("stairs_ramps", "پله و رمپ"),
       _n("finishes", "نازک‌کاری و Finish"),
       _n("schedules", "Scheduleهای معماری"),
       _n("architectural_takeoff", "متره معماری")),
    _n("structural", "سازه",
       _n("concrete", "سازه بتنی",
          _n("concrete_beams", "تیر"),
          _n("concrete_columns", "ستون"),
          _n("concrete_slabs", "دال"),
          _n("concrete_walls", "دیوار سازه‌ای"),
          _n("concrete_frames", "قاب"),
          _n("concrete_roofs", "سقف"),
          _n("concrete_stairs", "راه‌پله"),
          _n("concrete_reinforcement", "آرماتور، خاموت، سنجاقی، وصله و کوپلر"),
          _n("concrete_embeds", "قطعات مدفون و Embedded Items")),
       _n("steel", "سازه فولادی",
          _n("steel_beams", "تیر"),
          _n("steel_columns", "ستون"),
          _n("steel_bracing", "مهاربند"),
          _n("steel_frames", "قاب"),
          _n("steel_trusses", "خرپا"),
          _n("steel_plate_girders", "تیرورق و اعضای ساخته‌شده"),
          _n("steel_sections", "پروفیل‌ها و مقاطع"),
          _n("steel_plates", "ورق و سخت‌کننده"),
          _n("steel_connections", "اتصالات"),
          _n("steel_bolts", "پیچ، مهره، واشر و بولت"),
          _n("steel_welds", "جوش"),
          _n("steel_assemblies", "قطعات، Assembly و Part Number"),
          _n("steel_shop", "نقشه و اطلاعات ساخت"),
          _n("steel_takeoff", "متره فولاد")),
       _n("masonry", "سازه بنایی",
          _n("masonry_walls", "دیوارهای بنایی"),
          _n("masonry_bearing", "بنایی باربر"),
          _n("masonry_confined", "کلاف و اجزای محصورشده"),
          _n("masonry_openings", "بازشوها"),
          _n("masonry_materials", "مصالح و اجزا"),
          _n("masonry_takeoff", "متره بنایی")),
       _n("timber", "سازه چوبی",
          _n("timber_members", "اعضا"),
          _n("timber_frames", "قاب"),
          _n("timber_trusses", "خرپا"),
          _n("timber_connections", "اتصالات"),
          _n("timber_takeoff", "متره")),
       _n("composite", "سازه مرکب",
          _n("composite_beams", "تیر مرکب"),
          _n("composite_columns", "ستون مرکب"),
          _n("composite_slabs", "دال مرکب"),
          _n("composite_deck", "Deck و Stud"),
          _n("composite_connections", "اتصالات"),
          _n("composite_takeoff", "متره")),
       _n("precast", "سازه پیش‌ساخته",
          _n("precast_members", "قطعات"),
          _n("precast_connections", "اتصالات"),
          _n("precast_transport", "حمل"),
          _n("precast_installation", "نصب"),
          _n("precast_takeoff", "متره")),
       _n("special_structures", "سازه‌های خاص",
          _n("space_frame", "فضاکار"),
          _n("cable", "کابلی"),
          _n("shell", "پوسته"),
          _n("dome", "گنبد"),
          _n("special_truss", "سیستم‌های خرپایی خاص")),
       _n("foundations", "فونداسیون",
          _n("isolated_footing", "پی منفرد"),
          _n("strip_footing", "پی نواری"),
          _n("combined_footing", "پی مشترک"),
          _n("strap_footing", "پی باسکولی"),
          _n("mat", "پی گسترده / رادیه"),
          _n("pile", "شمع"),
          _n("pile_group", "گروه شمع"),
          _n("pile_cap", "کلاهک شمع"),
          _n("grade_beam", "شناژ"),
          _n("foundation_walls", "دیوارهای زیرزمین"),
          _n("foundation_connections", "اتصال سازه به پی"))),
    _n("analysis_design", "تحلیل و طراحی مهندسی",
       _n("modeling", "مدل‌سازی"),
       _n("loads", "بارگذاری"),
       _n("load_combinations", "ترکیب بار"),
       _n("static_analysis", "تحلیل استاتیکی"),
       _n("dynamic_analysis", "تحلیل دینامیکی"),
       _n("modal", "Modal"),
       _n("response_spectrum", "طیفی"),
       _n("time_history", "تاریخچه زمانی"),
       _n("p_delta", "P-Delta"),
       _n("results", "نتایج و کنترل‌ها")),
    _n("geotechnical", "ژئوتکنیک",
       _n("soil_profile", "مشخصات و لایه‌های خاک"),
       _n("bearing_capacity", "ظرفیت باربری"),
       _n("settlement", "نشست"),
       _n("groundwater", "آب زیرزمینی"),
       _n("tests", "آزمایش‌ها"),
       _n("geotech_report", "گزارش ژئوتکنیک"),
       _n("foundation_link", "ارتباط با فونداسیون")),
    _n("mechanical", "تأسیسات مکانیکی",
       _n("hvac", "HVAC"),
       _n("ventilation", "تهویه"),
       _n("heating_cooling", "گرمایش و سرمایش"),
       _n("plumbing", "آبرسانی و لوله‌کشی"),
       _n("drainage", "فاضلاب و آب باران"),
       _n("fire", "اطفای حریق"),
       _n("equipment", "تجهیزات"),
       _n("ducts_pipes", "کانال و لوله"),
       _n("mechanical_takeoff", "متره مکانیکی")),
    _n("electrical", "تأسیسات برقی",
       _n("lighting", "روشنایی"),
       _n("power", "برق و پریز"),
       _n("panels", "تابلوها"),
       _n("cables", "کابل و سیم"),
       _n("cable_trays", "سینی کابل"),
       _n("grounding", "ارت"),
       _n("fire_alarm", "اعلام حریق"),
       _n("low_current", "شبکه، دوربین و کنترل دسترسی"),
       _n("electrical_takeoff", "متره برقی")),
    _n("civil", "عمران و سایت",
       _n("site", "سایت و زمین"),
       _n("topography", "توپوگرافی"),
       _n("roads", "راه و مسیر"),
       _n("parking", "پارکینگ"),
       _n("drainage", "زهکشی"),
       _n("earthworks", "عملیات عمرانی"),
       _n("subbase_pavement", "زیرسازی و روسازی"),
       _n("civil_takeoff", "متره عمران")),
    _n("cad", "نقشه و CAD",
       _n("drawing_2d", "نقشه 2D"),
       _n("layers", "لایه‌ها"),
       _n("geometry", "هندسه و ترسیم"),
       _n("dimensions", "اندازه‌گذاری"),
       _n("annotation", "Annotation"),
       _n("blocks", "Block"),
       _n("hatch", "Hatch"),
       _n("details", "جزئیات"),
       _n("sheets", "شیت و Layout"),
       _n("print", "چاپ"),
       _n("dwg_dxf_pdf", "DWG / DXF / PDF")),
    _n("bim", "BIM / مدل سه‌بعدی",
       _n("model", "مدل سه‌بعدی"),
       _n("levels", "طبقات و Levelها"),
       _n("elements", "عناصر"),
       _n("properties", "Properties"),
       _n("families", "Objects / Families"),
       _n("materials", "مصالح"),
       _n("ifc", "IFC"),
       _n("import_export", "Import / Export"),
       _n("clash", "Clash Detection"),
       _n("coordination", "Coordination"),
       _n("validation", "Model Validation")),
    _n("takeoff", "متره و برداشت",
       _n("length", "طول"),
       _n("area", "سطح"),
       _n("volume", "حجم"),
       _n("count", "تعداد"),
       _n("weight", "وزن"),
       _n("drawing_takeoff", "متره از نقشه"),
       _n("bim_takeoff", "متره از BIM"),
       _n("multi_trade", "متره چندرشته‌ای")),
    _n("boq", "BOQ / فهرست مقادیر",
       _n("wbs", "WBS"),
       _n("item_codes", "کد آیتم"),
       _n("descriptions", "شرح"),
       _n("units", "واحد"),
       _n("quantities", "مقادیر"),
       _n("discipline_breakdown", "تفکیک رشته"),
       _n("location_breakdown", "تفکیک طبقه و ناحیه"),
       _n("boq_reports", "گزارش BOQ")),
    _n("estimating", "برآورد و قیمت‌گذاری",
       _n("materials", "مصالح"),
       _n("labor", "دستمزد"),
       _n("equipment", "ماشین‌آلات و تجهیزات"),
       _n("transport", "حمل"),
       _n("base_prices", "قیمت پایه"),
       _n("price_analysis", "آنالیز بها"),
       _n("coefficients", "ضرایب"),
       _n("adjustment", "تعدیل"),
       _n("direct_cost", "هزینه مستقیم"),
       _n("indirect_cost", "هزینه غیرمستقیم"),
       _n("final_estimate", "برآورد نهایی")),
    _n("cost_database", "بانک قیمت و داده",
       _n("price_lists", "فهرست‌بها"),
       _n("material_prices", "قیمت مصالح"),
       _n("labor_prices", "قیمت نیروی انسانی"),
       _n("equipment_prices", "قیمت تجهیزات"),
       _n("suppliers", "تأمین‌کنندگان"),
       _n("effective_dates", "تاریخ اعتبار"),
       _n("sources", "منبع"),
       _n("data_versions", "نسخه داده")),
    _n("contracts", "قرارداد و مالی",
       _n("contract_items", "اقلام قرارداد"),
       _n("quantities", "مقادیر قراردادی"),
       _n("rates", "نرخ‌ها"),
       _n("variations", "تغییر مقادیر"),
       _n("claims", "ادعاها و درخواست‌ها"),
       _n("contract_reports", "گزارش قرارداد")),
    _n("tender", "مناقصه و پیشنهاد قیمت",
       _n("tender_documents", "اسناد مناقصه"),
       _n("scope", "Scope"),
       _n("bid_boq", "BOQ مناقصه"),
       _n("bid_pricing", "قیمت‌گذاری پیشنهاد"),
       _n("bid_comparison", "مقایسه پیشنهادها")),
    _n("progress_payment", "پیشرفت و صورت‌وضعیت",
       _n("progress_measurement", "اندازه‌گیری پیشرفت"),
       _n("payment_items", "آیتم‌های صورت‌وضعیت"),
       _n("monthly_payment", "صورت‌وضعیت دوره‌ای"),
       _n("supporting_docs", "مستندات"),
       _n("payment_reports", "گزارش مالی")),
    _n("procurement", "خرید و تأمین",
       _n("material_requests", "درخواست خرید"),
       _n("purchase_orders", "سفارش خرید"),
       _n("vendors", "فروشندگان"),
       _n("deliveries", "تحویل"),
       _n("receipts", "رسید انبار"),
       _n("procurement_trace", "ردیابی تأمین")),
    _n("schedule", "زمان‌بندی و 4D",
       _n("activities", "فعالیت‌ها"),
       _n("dependencies", "روابط"),
       _n("baseline", "Baseline"),
       _n("progress", "پیشرفت"),
       _n("4d", "4D Model")),
    _n("cost_control", "کنترل هزینه و 5D",
       _n("budget", "بودجه"),
       _n("actual_cost", "هزینه واقعی"),
       _n("forecast", "پیش‌بینی"),
       _n("variance", "انحراف"),
       _n("5d", "5D")),
    _n("revision", "مدیریت تغییرات",
       _n("compare", "مقایسه نسخه‌ها"),
       _n("added", "Added"),
       _n("removed", "Removed"),
       _n("changed", "Changed"),
       _n("quantity_delta", "تغییر مقدار"),
       _n("cost_delta", "تغییر هزینه"),
       _n("drawing_delta", "تغییر نقشه"),
       _n("model_delta", "تغییر مدل"),
       _n("approval", "تأیید تغییر")),
    _n("audit", "Audit / Traceability",
       _n("audit_trail", "Audit Trail"),
       _n("lineage", "Traceability / Lineage"),
       _n("source", "منبع"),
       _n("user", "کاربر"),
       _n("timestamp", "زمان"),
       _n("before_after", "Before / After"),
       _n("audit_approval", "تأیید"),
       _n("history", "تاریخچه")),
    _n("standards", "استانداردها و آیین‌نامه‌ها",
       _n("iran", "استانداردها و مقررات ایران"),
       _n("international", "استانداردهای بین‌المللی"),
       _n("codes", "Code / Edition"),
       _n("effective_date", "تاریخ اعتبار"),
       _n("source", "منبع و مرجع")),
    _n("reports", "گزارش و خروجی",
       _n("project_reports", "گزارش پروژه"),
       _n("discipline_reports", "گزارش رشته‌ها"),
       _n("takeoff_reports", "گزارش متره"),
       _n("boq_reports", "گزارش BOQ"),
       _n("estimate_reports", "گزارش برآورد"),
       _n("revision_reports", "گزارش تغییرات"),
       _n("audit_reports", "گزارش Audit"),
       _n("excel", "Excel"),
       _n("pdf", "PDF"),
       _n("print", "چاپ")),
    _n("document_management", "مدیریت اسناد و همکاری",
       _n("document_register", "Document Register"),
       _n("transmittals", "Transmittal"),
       _n("permissions", "سطح دسترسی"),
       _n("comments", "یادداشت و کامنت"),
       _n("approvals", "گردش تأیید"),
       _n("collaboration", "همکاری تیمی")),
)


def flatten_product_map(node: ProductNode = MASTER_PRODUCT_MAP) -> tuple[ProductNode, ...]:
    """Return all nodes depth-first, including the root."""
    result: list[ProductNode] = []

    def walk(current: ProductNode) -> None:
        result.append(current)
        for child in current.children:
            walk(child)

    walk(node)
    return tuple(result)


def find_product_node(key: str) -> ProductNode | None:
    """Find a node by stable product-map key."""
    wanted = str(key or "").strip()
    return next((node for node in flatten_product_map() if node.key == wanted), None)
